---
version: "3"

tasks:
  format:
    cmds:
      - fd '.nix' | xargs nixfmt

  update:
    cmds:
      - nix flake update

  nh:
    cmds:
      - nh os switch .

  switch:
    cmds:
      - sudo nixos-rebuild switch --flake .

  update-switch:
    cmds:
      - task: update
      - task: switch

  switch-next-boot:
    cmds:
      - sudo nixos-rebuild boot --flake .

  build:
    cmds:
      - sudo nixos-rebuild build --flake .
