---
version: "3"

tasks:
  format:
    cmds:
      - fd '.nix' | xargs nixfmt

  update:
    cmds:
      - nix flake update

  nh:
    cmds:
      - nh os switch .

  switch:
    cmds:
      - sudo nixos-rebuild switch --flake .

  update-switch:
    cmds:
      - task: update
      - task: nh

  switch-next-boot:
    cmds:
      - sudo nixos-rebuild boot --flake .

  build:
    cmds:
      - sudo nixos-rebuild build --flake .

  home-switch:
    desc: "Apply home-manager configuration for current hostname"
    cmds:
      - nix run home-manager/release-24.11 -- switch --flake .#$(hostname)
