---
version: "3"

tasks:
  format:
    cmds:
      - fd '.nix' | xargs nixfmt

  update:
    cmds:
      - nix flake update

  switch:
    cmds:
      - sudo nixos-rebuild switch --flake .

  switch-next-boot:
    cmds:
      - sudo nixos-rebuild boot --flake .

  build:
    cmds:
      - sudo nixos-rebuild build --flake .
